[package]
name = "url_shortener"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
rocket = "0.5.0-rc.2"
shuttle-service = { version = "0.7", features = ["web-rocket"] }
shuttle-aws-rds = { version = "0.7", features = ["postgres"] }
sqlx = "0.6"
url = "2.3"
nanoid = "0.4"
